project:
  type: book

book:
  title: "CMC5105 - 수학교육통계분석: 회귀모형과 경시적 자료분석"
  author: "최영근" 
  date: "8/30/2024"
  chapters:
    - index.qmd
    - R-1-basics.qmd
    - R-2-vec-mat.qmd
    - R-3-statements.qmd
    - R-4-list-dfs-io.qmd
    - R-5-vis-basic.qmd
    - simple-linear-regression.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

